/** Achievement names follow the game's catalog; descriptions state this recreation's conditions. */
export const ACHIEVEMENTS = {
    THE_GUARDIAN: ['The Guardian', 'Defeat the Guardian.'],
    THE_GHOST: ['The Ghost', 'Defeat Hexaghost.'],
    THE_BOSS: ['The Boss', 'Defeat Slime Boss.'],
    THE_CHAMPION: ['The Champion', 'Defeat the Champ.'],
    THE_AUTOMATON: ['The Automaton', 'Defeat Bronze Automaton.'],
    THE_COLLECTOR: ['The Collector', 'Defeat the Collector.'],
    THE_SHAPES: ['The Shapes', 'Defeat Donu and Deca.'],
    THE_CROW: ['The Crow', 'Defeat both phases of the Awakened One.'],
    THE_TIME_EATER: ['The Time Eater', 'Defeat Time Eater.'],
    ASCEND_0: ['Ascend 0', 'Clear Act 3 and unlock Ascension.'],
    ASCEND_10: ['Ascend 10', 'Clear Act 3 at Ascension 10 or higher.'],
    ASCEND_20: ['Ascend 20', 'Clear Act 3 at Ascension 20.'],
    THE_PACT: ['The Pact', 'Exhaust at least 20 cards in one fight.'],
    ADRENALINE: ['Adrenaline', 'Reach 9 Energy during combat.'],
    SHRUG_IT_OFF: ['Shrug It Off', 'Finish a fight with exactly 1 HP.'],
    PERFECT: ['Perfect', 'Defeat a boss without losing HP to enemies.'],
    RUBY: ['Ruby', 'Clear Act 3 as Ironclad.'],
    EMERALD: ['Emerald', 'Clear Act 3 as Silent.'],
    SAPPHIRE: ['Sapphire', 'Clear Act 3 as Defect.'],
    AMETHYST: ['Amethyst', 'Clear Act 3 as Watcher.'],
    COME_AT_ME: ['Come At Me', 'Win a fight without playing an Attack.'],
    PLAGUE: ['Plague', 'Kill three enemies with Poison in one fight.'],
    IMPERVIOUS: ['Impervious', 'Reach 99 Block during combat.'],
    BARRICADED: ['Barricaded', 'Reach 999 Block during combat.'],
    CATALYST: ['Catalyst', 'Put at least 99 Poison on one enemy.'],
    POWERFUL: ['Powerful', 'Have ten different buffs active together.'],
    NINJA: ['Ninja', 'Play ten Shivs in one turn.'],
    MY_LUCKY_DAY: ['My Lucky Day', 'Win a Daily Climb.'],
    INFINITY: ['Infinity', 'Play at least 25 cards in one turn.'],
    JAXXED: ['Jaxxed', 'Reach 50 Strength during combat.'],
    PURITY: ['Purity', 'After floor 3, have at most three cards across hand, draw, and discard.'],
    RUBY_PLUS: ['Ruby+', 'Defeat the Heart as Ironclad.'],
    EMERALD_PLUS: ['Emerald+', 'Defeat the Heart as Silent.'],
    SAPPHIRE_PLUS: ['Sapphire+', 'Defeat the Heart as Defect.'],
    AMETHYST_PLUS: ['Amethyst+', 'Defeat the Heart as Watcher.'],
    THE_TRANSIENT: ['The Transient', 'Kill the Transient before it fades.'],
    THE_END: ['The End?', 'Defeat the Heart as Ironclad, Silent, and Defect.'],
    YOU_ARE_NOTHING: ['You Are Nothing', 'Defeat a boss on the first turn.'],
    OOH_DONUT: ['Ooh Donut!', 'Kill Donu using Feed.'],
    SPEED_CLIMBER: ['Speed Climber', 'Clear Act 3 in under 20 minutes.'],
    NEON: ['Neon', 'Channel nine Plasma orbs in one turn.'],
    FOCUSED: ['Focused', 'Reach 25 Focus during combat.'],
    MINIMALIST: ['Minimalist', 'Clear Act 3 with five or fewer cards in your deck.'],
    COMMON_SENSE: ['Common Sense', 'Clear Act 3 with no uncommon or rare cards in your deck.'],
    WHO_NEEDS_RELICS: ['Who Needs Relics?', 'Clear Act 3 with exactly one relic.'],
    ETERNAL_ONE: ['Eternal One', 'Earn every other achievement.'],
} as const
export type AchievementId = keyof typeof ACHIEVEMENTS
export const ACHIEVEMENT_IDS = Object.keys(ACHIEVEMENTS) as AchievementId[]
export interface UnlockNotice { id: string; title: string; detail: string }
export interface AchievementCombat { exhausted: number; attacks: number; shivs: number; plasma: number; poisonKills: string[] }
