import { obtainCurse } from '../run'
import type { RelicDef } from '../relics'
/** Passive rules are applied in the corresponding damage, play, turn, and pile operations. */
export const COMBAT_RULE_RELICS = {
    CALIPERS: { id: 'CALIPERS', name: 'Calipers', rarity: 'rare', description: 'Lose only 15 Block at turn start.' },
    ICE_CREAM: { id: 'ICE_CREAM', name: 'Ice Cream', rarity: 'rare', description: 'Keep unused Energy between turns.' },
    RUNIC_PYRAMID: { id: 'RUNIC_PYRAMID', name: 'Runic Pyramid', rarity: 'boss', description: 'Do not discard your hand at turn end.' },
    RUNIC_DOME: { id: 'RUNIC_DOME', name: 'Runic Dome', rarity: 'boss', energyPerTurn: 1, description: 'Gain 1 Energy each turn. Enemy intents are hidden.' },
    VELVET_CHOKER: { id: 'VELVET_CHOKER', name: 'Velvet Choker', rarity: 'boss', energyPerTurn: 1, description: 'Gain 1 Energy each turn. Play at most 6 cards per turn.' },
    SLAVERS_COLLAR: { id: 'SLAVERS_COLLAR', name: "Slaver's Collar", rarity: 'boss', description: 'Gain 1 Energy each turn in elite and boss combats.', onPlayerTurnStart: ({ engine }) => { if (engine.state.enemies.some(e => e.tags?.some(tag => tag === 'elite' || tag === 'boss'))) engine.enqueue({ kind: 'GainEnergy', amount: 1 }) } },
    VIOLET_LOTUS: { id: 'VIOLET_LOTUS', name: 'Violet Lotus', rarity: 'boss', character: 'watcher', description: 'Gain 1 extra Energy when leaving Calm.' },
    GOLD_PLATED_CABLES: { id: 'GOLD_PLATED_CABLES', name: 'Gold-Plated Cables', rarity: 'uncommon', character: 'defect', description: 'Your next orb triggers its passive an additional time each turn.' },
    GOLDEN_EYE: { id: 'GOLDEN_EYE', name: 'Golden Eye', rarity: 'rare', character: 'watcher', description: 'Scry 2 extra cards.' },
    SNECKO_SKULL: { id: 'SNECKO_SKULL', name: 'Snecko Skull', rarity: 'common', character: 'silent', description: 'Apply 1 extra Poison whenever you apply Poison.' },
    CHAMPION_BELT: { id: 'CHAMPION_BELT', name: 'Champion Belt', rarity: 'rare', character: 'ironclad', description: 'Applying Vulnerable also applies 1 Weak.' },
    GINGER: { id: 'GINGER', name: 'Ginger', rarity: 'rare', description: 'You cannot become Weak.' },
    TURNIP: { id: 'TURNIP', name: 'Turnip', rarity: 'rare', description: 'You cannot become Frail.' },
    TORII: { id: 'TORII', name: 'Torii', rarity: 'rare', description: 'Reduce unblocked attack damage of 5 or less to 1.' },
    TUNGSTEN_ROD: { id: 'TUNGSTEN_ROD', name: 'Tungsten Rod', rarity: 'rare', description: 'Lose 1 less HP each time you lose HP.' },
    THE_BOOT: { id: 'THE_BOOT', name: 'The Boot', rarity: 'common', description: 'Increase unblocked attack damage from 1–4 to 5.' },
    PAPER_KRANE: { id: 'PAPER_KRANE', name: 'Paper Krane', rarity: 'uncommon', character: 'silent', description: 'Weak enemies deal 40% less attack damage.' },
    ODD_MUSHROOM: { id: 'ODD_MUSHROOM', name: 'Odd Mushroom', rarity: 'event', description: 'While Vulnerable, take 25% extra attack damage.' },
    RED_SKULL: { id: 'RED_SKULL', name: 'Red Skull', rarity: 'common', character: 'ironclad', description: 'Have 3 extra Strength while at or below half HP.' },
    STRIKE_DUMMY: { id: 'STRIKE_DUMMY', name: 'Strike Dummy', rarity: 'uncommon', description: 'Cards with Strike in their name deal 3 extra damage.' },
    WRIST_BLADE: { id: 'WRIST_BLADE', name: 'Wrist Blade', rarity: 'boss', character: 'silent', description: 'Attacks that cost 0 deal 4 extra damage.' },
    CHEMICAL_X: { id: 'CHEMICAL_X', name: 'Chemical X', rarity: 'shop', description: 'Increase X-cost card effects by 2.' },
    GREMLIN_HORN: { id: 'GREMLIN_HORN', name: 'Gremlin Horn', rarity: 'uncommon', description: 'Gain 1 Energy and draw 1 when an enemy dies.' },
    THE_SPECIMEN: { id: 'THE_SPECIMEN', name: 'The Specimen', rarity: 'rare', character: 'silent', description: 'Transfer Poison from a dying enemy to another enemy.' },
    HAND_DRILL: { id: 'HAND_DRILL', name: 'Hand Drill', rarity: 'shop', description: 'Apply 2 Vulnerable when you break an enemy’s Block.' },
    STRANGE_SPOON: { id: 'STRANGE_SPOON', name: 'Strange Spoon', rarity: 'shop', description: 'Cards exhausted by playing them have a 50% chance to discard instead.' },
    BLUE_CANDLE: { id: 'BLUE_CANDLE', name: 'Blue Candle', rarity: 'uncommon', description: 'Play unplayable Curses, losing 1 HP and exhausting them.' },
    MEDICAL_KIT: { id: 'MEDICAL_KIT', name: 'Medical Kit', rarity: 'shop', description: 'Play unplayable Status cards to exhaust them.' },
    UNCEASING_TOP: { id: 'UNCEASING_TOP', name: 'Unceasing Top', rarity: 'rare', description: 'Draw a card whenever your hand is empty during your turn.' },
    NECRONOMICON: { id: 'NECRONOMICON', name: 'Necronomicon', rarity: 'event', onAcquire: run => { obtainCurse(run, 'NECRONOMICURSE') }, description: 'Each turn, repeat your first Attack costing at least 2. Obtain Necronomicurse on pickup.' },
} satisfies Record<string, RelicDef>
