import { expect, test } from '@playwright/test'
import { activate, button, downloadProfile, open, scene, watch } from './driver'

for (const character of ['Ironclad', 'Silent', 'Defect', 'Watcher']) test(`${character} starts, plays a card, ends a turn and reloads in the built game`, async ({ page }, info) => {
    const observed = watch(page)
    await open(page)
    await activate(page, new RegExp(`^${character}:`)); await activate(page, 'Seeded')
    await page.getByRole('textbox', { name: 'Run seed' }).fill('release-0')
    await activate(page, 'New Run'); await expect(scene(page, 'Neow')).toBeVisible()
    await activate(page, /^Gain 10% max HP/); await expect(scene(page, 'Map')).toBeVisible()
    await activate(page, /^Floor .*Fight/); await expect(scene(page, 'Combat')).toBeVisible()
    const openingHand = await button(page, /^Play /).allTextContents()
    const openingSummary = await scene(page, 'Combat').locator('.access-tree > p').first().textContent()
    const initialCount = openingHand.length
    const play = button(page, /^Play (Strike|Defend)/).first(), label = await play.textContent()
    await play.press('Enter')
    if (label!.startsWith('Play Strike')) await activate(page, /^Target /)
    await expect(button(page, /^Play /)).toHaveCount(initialCount - 1)
    await activate(page, 'End Turn')
    await expect(scene(page, 'Combat').getByRole('status')).toContainText('Turn 2.')
    const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('sts_run_v7')!))
    expect(saved.character).toBe(character.toLowerCase()); expect(saved.pendingRoom.scene).toBe('Combat')
    await expect.poll(() => observed.resources.some(url => /\/art\/cards[^/]*\.webp$/.test(url))).toBe(true)
    expect(await page.evaluate(() => document.fonts.check('16px Barlow'))).toBe(true)
    await info.attach(`${character.toLowerCase()}-combat`, { body: await page.screenshot(), contentType: 'image/png' })
    await page.reload(); await expect(scene(page, 'MainMenu')).toBeVisible()
    await activate(page, 'Continue'); await expect(scene(page, 'Combat')).toBeVisible()
    await expect(button(page, /^Play /)).toHaveText(openingHand)
    await expect(scene(page, 'Combat').locator('.access-tree > p').first()).toHaveText(openingSummary!)
    expect(observed.errors).toEqual([]); expect(observed.missing).toEqual([])
    expect(observed.resources.some(url => /\/src\/|\/tests\/browser\//.test(url))).toBe(false)
})

test('guide keyboard focus, settings and profile downloads work in the built game', async ({ page }) => {
    const observed = watch(page)
    await open(page)
    // Traverse the shipped semantic controls with actual Tab/Enter input.
    const help = button(page, 'Help')
    for (let i = 0; i < 30 && !(await help.evaluate(node => node === document.activeElement)); i++) await page.keyboard.press('Tab')
    await expect(help).toBeFocused(); await page.keyboard.press('Enter')
    const guide = page.getByRole('dialog', { name: 'Game guide' })
    await expect(guide).toBeVisible()
    await activate(page, 'Status effects'); await page.getByRole('searchbox').fill('poison')
    await expect(guide).toContainText('Poison')
    await page.keyboard.press('Escape'); await expect(help).toBeFocused()
    await activate(page, 'New Run'); await activate(page, /^Gain 10% max HP/)
    await expect(scene(page, 'Map')).toBeVisible(); await activate(page, 'Menu')
    await activate(page, 'Settings'); await activate(page, 'Sound: on')
    await expect(button(page, 'Sound: off')).toBeEnabled()
    await activate(page, 'Profile backup'); await expect(scene(page, 'Profile')).toBeVisible()
    const exported = await downloadProfile(page), profile = JSON.parse(exported.buffer.toString())
    expect(exported.name).toMatch(/^spire-profile-.*\.json$/)
    expect(profile.format).toBe('rookmate.spire.profile'); expect(profile.run.neowCompleted).toBe(true)
    expect(profile.settings.sound).toBe(false)
    await page.getByLabel('Import profile file').setInputFiles({ name: exported.name, mimeType: 'application/json', buffer: exported.buffer })
    await activate(page, 'Replace profile')
    await expect(scene(page, 'Profile')).toContainText('Profile imported.')
    await page.reload(); await expect(scene(page, 'MainMenu')).toBeVisible()
    await activate(page, 'Continue'); await expect(scene(page, 'Map')).toBeVisible()
    expect(observed.errors).toEqual([]); expect(observed.missing).toEqual([])
})
