import { createCombatCard } from '../combat/cardCreation'
import type { CardDef } from '../state'

export const STATUS_CARDS: Record<string, CardDef> = {
    NECRONOMICURSE: { id: 'NECRONOMICURSE', name: 'Necronomicurse', type: 'curse', cost: 0, unplayable: true, removable: false, poolEnabled: false, description: () => 'Cannot be removed. Returns to hand when exhausted.', onExhaust: ({ engine, card }) => engine.insertCard(createCombatCard(engine, card), 'hand') },
    CURSE_OF_THE_BELL: { id: 'CURSE_OF_THE_BELL', name: 'Curse of the Bell', type: 'curse', cost: 0, unplayable: true, removable: false, poolEnabled: false, description: () => 'Cannot be removed.' },
    PRIDE: { id: 'PRIDE', name: 'Pride', type: 'curse', cost: 1, innate: true, exhaust: true, poolEnabled: false, description: () => 'At turn end, put a copy on top of your draw pile.' },
    DOUBT: { id: 'DOUBT', name: 'Doubt', type: 'curse', cost: 0, unplayable: true, poolEnabled: false, description: () => 'At turn end, gain 1 Weak.' },
    SHAME: { id: 'SHAME', name: 'Shame', type: 'curse', cost: 0, unplayable: true, poolEnabled: false, description: () => 'At turn end, gain 1 Frail.' },
    DECAY: { id: 'DECAY', name: 'Decay', type: 'curse', cost: 0, unplayable: true, poolEnabled: false, description: () => 'At turn end, take 2 damage.' },
    WRITHE: { id: 'WRITHE', name: 'Writhe', type: 'curse', cost: 0, unplayable: true, innate: true, poolEnabled: false },
    NORMALITY: { id: 'NORMALITY', name: 'Normality', type: 'curse', cost: 0, unplayable: true, poolEnabled: false, description: () => 'While in hand, you cannot play more than 3 cards per turn.' },
    VOID: { id: 'VOID', name: 'Void', type: 'status', cost: 0, unplayable: true, ethereal: true, poolEnabled: false },
    ASCENDERS_BANE: { id: 'ASCENDERS_BANE', removable: false, name: "Ascender's Bane", type: 'curse', cost: 0, unplayable: true, ethereal: true, poolEnabled: false },
    WOUND: {
        id: 'WOUND',
        name: 'Wound',
        type: 'status',
        cost: 0,
        unplayable: true,
        poolEnabled: false,
        targeting: { type: 'none' },
    },
    DAZED: {
        id: 'DAZED',
        name: 'Dazed',
        type: 'status',
        cost: 0,
        unplayable: true,
        ethereal: true,
        poolEnabled: false,
        targeting: { type: 'none' },
    },
    BURN: {
        id: 'BURN',
        name: 'Burn',
        type: 'status',
        cost: 0,
        unplayable: true,
        poolEnabled: false,
        targeting: { type: 'none' },
    },
    SLIMED: {
        id: 'SLIMED',
        name: 'Slimed',
        type: 'status',
        cost: 1,
        exhaust: true,
        poolEnabled: false,
        targeting: { type: 'none' },
    },
    INJURY: {
        id: 'INJURY',
        name: 'Injury',
        type: 'curse',
        cost: 0,
        unplayable: true,
        poolEnabled: false,
        targeting: { type: 'none' },
    },
    CLUMSY: {
        id: 'CLUMSY',
        name: 'Clumsy',
        type: 'curse',
        cost: 0,
        unplayable: true,
        ethereal: true,
        poolEnabled: false,
        targeting: { type: 'none' },
    },
    REGRET: {
        id: 'REGRET',
        name: 'Regret',
        type: 'curse',
        cost: 0,
        unplayable: true,
        poolEnabled: false,
        targeting: { type: 'none' },
    },
    PAIN: {
        id: 'PAIN',
        name: 'Pain',
        type: 'curse',
        cost: 0,
        unplayable: true,
        poolEnabled: false,
        targeting: { type: 'none' },
    },
    PARASITE: {
        id: 'PARASITE',
        name: 'Parasite',
        type: 'curse',
        cost: 0,
        unplayable: true,
        poolEnabled: false,
        targeting: { type: 'none' },
    },
}
