import type { CardDef } from '../state'

export const STATUS_CARDS: Record<string, CardDef> = {
    WOUND: {
        id: 'WOUND',
        name: 'Wound',
        type: 'status',
        cost: 0,
        unplayable: true,
        poolEnabled: false,
        targeting: { type: 'none' },
    },
    DAZED: {
        id: 'DAZED',
        name: 'Dazed',
        type: 'status',
        cost: 0,
        unplayable: true,
        ethereal: true,
        poolEnabled: false,
        targeting: { type: 'none' },
    },
    BURN: {
        id: 'BURN',
        name: 'Burn',
        type: 'status',
        cost: 0,
        unplayable: true,
        poolEnabled: false,
        targeting: { type: 'none' },
    },
    SLIMED: {
        id: 'SLIMED',
        name: 'Slimed',
        type: 'status',
        cost: 1,
        exhaust: true,
        poolEnabled: false,
        targeting: { type: 'none' },
    },
    INJURY: {
        id: 'INJURY',
        name: 'Injury',
        type: 'curse',
        cost: 0,
        unplayable: true,
        poolEnabled: false,
        targeting: { type: 'none' },
    },
    CLUMSY: {
        id: 'CLUMSY',
        name: 'Clumsy',
        type: 'curse',
        cost: 0,
        unplayable: true,
        ethereal: true,
        poolEnabled: false,
        targeting: { type: 'none' },
    },
    REGRET: {
        id: 'REGRET',
        name: 'Regret',
        type: 'curse',
        cost: 0,
        unplayable: true,
        poolEnabled: false,
        targeting: { type: 'none' },
    },
    PAIN: {
        id: 'PAIN',
        name: 'Pain',
        type: 'curse',
        cost: 0,
        unplayable: true,
        poolEnabled: false,
        targeting: { type: 'none' },
    },
    PARASITE: {
        id: 'PARASITE',
        name: 'Parasite',
        type: 'curse',
        cost: 0,
        unplayable: true,
        poolEnabled: false,
        targeting: { type: 'none' },
    },
}
