import { CARD_DEFS, canRemoveCard, canUpgradeCard, resolveCard } from '../cards'
import { POTION_DEFS } from '../potions'
import { RELIC_DEFS } from '../relics'
import type { RelicId } from '../run'
import { choice, cost, event, leave, remove, transform, upgrade, worse } from './helpers'
export const ADDITIONAL_EVENTS = {
    WING_STATUE: event('WING_STATUE', 'Wing Statue', 'A broken statue holds a purse above a narrow opening.', () => [remove('WING_PRAY', 'Pray', 'Lose 7 HP. Remove 1 card.'), choice('WING_DESTROY', 'Destroy', 'Gain 50–80 Gold.', { disabled: r => !r.deck.some(c => (resolveCard(c).baseDamage ?? 0) >= 10) }), leave()]),
    SHINING_LIGHT: event('SHINING_LIGHT', 'Shining Light', 'Two cards can be strengthened in the searing light.', run => [choice('LIGHT_ENTER', 'Enter', `Lose ${worse(run, 20, 30)}% max HP. Upgrade 2 random cards.`, { disabled: r => !r.deck.some(canUpgradeCard) }), leave()]),
    MUSHROOMS: event('MUSHROOMS', 'Mushrooms', 'A cluster of mushrooms blocks the passage.', () => [choice('MUSHROOM_FIGHT', 'Stomp', 'Fight 3 Fungi Beasts. Obtain Odd Mushroom.'), choice('MUSHROOM_EAT', 'Eat', 'Heal 25% max HP. Obtain Parasite.')], r => r.floor > 6),
    DEAD_ADVENTURER: event('DEAD_ADVENTURER', 'Dead Adventurer', 'An elite has left a fallen adventurer behind.', r => [choice('ADVENTURER_SEARCH', 'Search', `${Math.min(100, worse(r, 25, 35) + (r.eventState?.attempts ?? 0) * 25)}% chance the elite returns. Find Gold, a relic, or nothing.`), leave()], r => r.floor > 6),
    AUGMENTER: event('AUGMENTER', 'Augmenter', 'A stranger offers three experimental treatments.', r => r.eventState?.step === 'transform' ? [transform('AUGMENT_TRANSFORM')] : [choice('AUGMENT_JAX', 'Test J.A.X.', 'Obtain J.A.X.'), { ...transform('AUGMENT_TRANSFORM'), description: 'Transform 2 cards.', disabled: run => run.deck.filter(canRemoveCard).length < 2 }, choice('AUGMENT_MUTAGEN', 'Ingest mutagens', 'Obtain Mutagenic Strength.')]),
    COUNCIL_OF_GHOSTS: event('COUNCIL_OF_GHOSTS', 'Council of Ghosts', 'The ghosts offer protection at a permanent cost.', r => [choice('GHOST_ACCEPT', 'Accept', `Lose 50% max HP. Obtain ${worse(r, 5, 3)} Apparitions.`), leave()]),
    VAMPIRES: event('VAMPIRES', 'Vampires', 'A new appetite can replace your old attacks.', () => [choice('VAMPIRE_ACCEPT', 'Accept', 'Lose 30% max HP. Replace all Strikes with 5 Bites.'), choice('VAMPIRE_VIAL', 'Offer Blood Vial', 'Lose Blood Vial. Replace all Strikes with 5 Bites.', { disabled: r => !r.relics.includes('BLOOD_VIAL') }), leave()]),
    CURSED_TOME: event('CURSED_TOME', 'Cursed Tome', 'A book pulls you deeper with each page.', r => (r.eventState?.attempts ?? 0) >= 3 ? [choice('TOME_TAKE', 'Take', `Lose ${worse(r, 10, 15)} HP. Obtain a book relic.`), choice('TOME_STOP', 'Stop', 'Lose 3 HP.')] : [choice('TOME_READ', 'Read', `Lose ${(r.eventState?.attempts ?? 0) + 1} HP.`), leave()]),
    THE_NEST: event('THE_NEST', 'The Nest', 'Cultists queue beside a pile of offerings.', r => [choice('NEST_DAGGER', 'Stay in line', 'Lose 6 HP. Obtain Ritual Dagger.'), choice('NEST_GOLD', 'Smash and grab', `Gain ${worse(r, 99, 50)} Gold.`)]),
    MASKED_BANDITS: event('MASKED_BANDITS', 'Masked Bandits', 'Three bandits demand your purse.', () => [choice('BANDITS_PAY', 'Pay', 'Lose all Gold.'), choice('BANDITS_FIGHT', 'Fight', 'Fight Pointy, Romeo, and Bear. Obtain Red Mask.')]),
    COLOSSEUM: event('COLOSSEUM', 'The Colosseum', 'The arena gates close behind you.', r => r.eventState?.step === 'second' ? [choice('COLOSSEUM_SECOND', 'Victory', 'Fight Gremlin Nob and Taskmaster. Gain 100 Gold, an uncommon and a rare relic.'), leave()] : [choice('COLOSSEUM_FIRST', 'Fight', 'Defeat a Red Slaver and a Blue Slaver.')], r => r.floor >= 25),
    PLEADING_VAGRANT: event('PLEADING_VAGRANT', 'Pleading Vagrant', 'A vagrant offers a relic for help.', () => [choice('VAGRANT_GOLD', 'Offer Gold', 'Pay 85 Gold. Obtain a relic.', { disabled: cost(85) }), choice('VAGRANT_ROB', 'Rob', 'Obtain a relic and Shame.'), leave()]),
    PURIFIER: event('PURIFIER', 'Purifier', 'The shrine can release a burden.', () => [remove('PURIFIER_REMOVE', 'Pray'), leave()]),
    DIVINE_FOUNTAIN: event('DIVINE_FOUNTAIN', 'The Divine Fountain', 'Clear water promises relief from curses.', () => [choice('FOUNTAIN_DRINK', 'Drink', 'Remove all removable Curses.'), leave()], r => r.deck.some(c => CARD_DEFS[c.defId].type === 'curse' && canRemoveCard(c))),
    BONFIRE_SPIRITS: event('BONFIRE_SPIRITS', 'Bonfire Spirits', 'Offer a card to the fire. Its rarity determines the gift.', () => [remove('BONFIRE_OFFER', 'Offer a card', 'Common: heal 5. Uncommon: heal fully. Rare: +10 max HP and full heal. Curse: Spirit Poop.')]),
    OMINOUS_FORGE: event('OMINOUS_FORGE', 'Ominous Forge', 'The forge still holds heat and a hidden tool.', () => [upgrade('FORGE_UPGRADE'), choice('FORGE_RUMMAGE', 'Rummage', 'Obtain Warped Tongs and Pain.'), leave()]),
    LAB: event('LAB', 'Lab', 'Abandoned shelves hold three potions.', () => [choice('LAB_SEARCH', 'Search', 'Obtain 3 potions.')]),
    WOMAN_IN_BLUE: event('WOMAN_IN_BLUE', 'The Woman in Blue', 'A potion seller offers a choice of bundles.', r => [1, 2, 3].map(n => choice(`WOMAN_${n}`, `Buy ${n} potion${n > 1 ? 's' : ''}`, `Pay ${10 + n * 10} Gold.`, { disabled: cost(10 + n * 10) })).concat(choice('WOMAN_LEAVE', 'Leave', r.asc >= 15 ? 'Lose 5% max HP.' : '')), r => r.gold >= 50),
    FACE_TRADER: event('FACE_TRADER', 'Face Trader', 'A collector reaches toward your face.', r => [choice('FACE_TOUCH', 'Touch', `Lose 10% max HP. Gain ${worse(r, 75, 50)} Gold.`), choice('FACE_TRADE', 'Trade', 'Obtain a random face relic.'), leave()], r => r.act <= 2),
    KNOWING_SKULL: event('KNOWING_SKULL', 'Knowing Skull', 'The skull answers each request with a price in blood.', r => ['POTION', 'GOLD', 'CARD', 'LEAVE'].map(id => choice(`SKULL_${id}`, { POTION: 'A pick-me-up', GOLD: 'Riches', CARD: 'Success', LEAVE: 'How do I leave?' }[id]!, `Lose ${6 + (r.eventState?.counts?.[id] ?? 0)} HP.${id === 'POTION' ? ' Obtain a potion.' : id === 'GOLD' ? ' Gain 90 Gold.' : id === 'CARD' ? ' Obtain a colorless card.' : ''}`)), r => r.act === 2 && r.player.hp > 12),
    NLOTH: event('NLOTH', "N'loth", 'A strange creature is hungry for a relic.', r => (r.eventState?.relics ?? []).map(id => choice(`NLOTH_${id}`, `Offer ${RELIC_DEFS[id as RelicId].name}`, "Lose this relic. Obtain N'loth's Gift.")).concat(leave()), r => r.act === 2 && r.relics.length >= 2 && !r.relics.includes('NLOTHS_GIFT')),
    DESIGNER: event('DESIGNER', 'Designer In-Spire', 'The designer proposes changes to your deck.', r => {
        if (r.eventState?.step === 'transform') return [transform('DESIGN_TRANSFORM')]
        const randomUpgrade = r.eventState?.counts?.randomUpgrade, twoTransforms = r.eventState?.counts?.twoTransforms
        const adjustment = worse(r, 40, 50), cleanup = worse(r, 60, 75), full = worse(r, 90, 110)
        return [choice(randomUpgrade ? 'DESIGN_RANDOM' : 'DESIGN_UPGRADE', 'Adjustments', `Pay ${adjustment}. ${randomUpgrade ? 'Upgrade 2 random cards.' : 'Upgrade a card.'}`, { requiresSelection: randomUpgrade ? undefined : 'upgrade', disabled: run => run.gold < adjustment || !run.deck.some(canUpgradeCard) }),
            choice(twoTransforms ? 'DESIGN_TRANSFORM' : 'DESIGN_REMOVE', 'Clean up', `Pay ${cleanup}. ${twoTransforms ? 'Transform 2 cards.' : 'Remove a card.'}`, { requiresSelection: twoTransforms ? 'transform' : 'remove', disabled: run => run.gold < cleanup || run.deck.filter(canRemoveCard).length < (twoTransforms ? 2 : 1) }),
            { ...remove('DESIGN_FULL', 'Full service', `Pay ${full}. Remove a card, then upgrade a random card.`), disabled: run => run.gold < full || !run.deck.some(canRemoveCard) }, choice('DESIGN_PUNCH', 'Punch', `Lose ${worse(r, 3, 5)} HP.`)]
    }, r => r.act >= 2 && r.gold >= 75),
    WE_MEET_AGAIN: event('WE_MEET_AGAIN', 'We Meet Again!', 'The traveler requests a specific gift in exchange for a relic.', r => {
        const state = r.eventState!, potion = state.potionId, card = r.deck.find(c => c.instanceId === state.cards?.[0])
        return [choice('MEET_POTION', 'Give potion', potion ? `Give ${POTION_DEFS[potion].name}. Obtain a relic.` : 'No potion to give.', { disabled: () => !potion || !r.potions.includes(potion) }), choice('MEET_GOLD', 'Give Gold', `Give ${state.gold ?? 50} Gold. Obtain a relic.`, { disabled: cost(state.gold ?? 50) }), choice('MEET_CARD', 'Give card', card ? `Give ${resolveCard(card).name}. Obtain a relic.` : 'No eligible card.', { disabled: () => !card }), leave()]
    }),
    NOTE_FOR_YOURSELF: event('NOTE_FOR_YOURSELF', 'A Note for Yourself', 'A card was left here for a future climb.', r => [remove('NOTE_TRADE', 'Take and give', `Receive ${r.eventState?.noteCard ? resolveCard({ instanceId: 'note', ...r.eventState.noteCard }).name : 'Iron Wave'}. Store one of your cards.`), leave()], r => r.mode !== 'daily' && r.asc < 15),
    MATCH_AND_KEEP: event('MATCH_AND_KEEP', 'Match and Keep', 'Turn over two cards. Matching pairs are added to your deck, including Curses.', () => []),
}
