import { canUpgradeCard, resolveCard } from '../cards'
import type { RunState } from '../run'
import type { EventChoiceDef, EventDef, EventId } from './model'

const choice = (id: string, label: string, description = '', extra: Partial<EventChoiceDef> = {}): EventChoiceDef => ({ id, label, description, ...extra })
const leave = () => choice('LEAVE', 'Leave')
const worse = (run: RunState, normal: number, asc: number) => run.asc >= 15 ? asc : normal
const cost = (amount: number) => (run: RunState) => run.gold < amount
const remove = (id: string, label: string, description = 'Remove 1 card.'): EventChoiceDef => choice(id, label, description, { requiresSelection: 'remove', disabled: run => !run.deck.some(c => c.defId !== 'ASCENDERS_BANE') })
const upgrade = (id: string): EventChoiceDef => choice(id, 'Upgrade', 'Upgrade 1 card.', { requiresSelection: 'upgrade', disabled: run => !run.deck.some(canUpgradeCard) })
const transform = (id: string): EventChoiceDef => choice(id, 'Transform', 'Transform 1 card.', { requiresSelection: 'transform', disabled: run => !run.deck.some(c => c.defId !== 'ASCENDERS_BANE') })
const event = (id: EventId, title: string, body: string, choices: EventDef['choices'], eligible?: EventDef['eligible']): EventDef => ({ id, title, body, choices, eligible })

export const EVENT_DEFS: Record<EventId, EventDef> = {
    WORLD_OF_GOOP: event('WORLD_OF_GOOP', 'World of Goop', 'Gold lies beneath a pool of burning slime.', run => [choice('WORLD_OF_GOOP_REACH', 'Reach in', 'Lose 11 HP. Gain 75 Gold.'), choice('WORLD_OF_GOOP_LEAVE', 'Leave', `Lose ${run.asc >= 15 ? '35–75' : '20–50'} Gold.`)]),
    CLERIC: event('CLERIC', 'The Cleric', 'A cleric offers healing and a lighter deck.', run => [choice('CLERIC_HEAL', 'Heal', 'Pay 35 Gold. Heal 25% max HP.', { disabled: cost(35) }), { ...remove('CLERIC_PURGE', 'Purge', `Pay ${worse(run, 50, 75)} Gold. Remove 1 card.`), disabled: cost(worse(run, 50, 75)) }, leave()], run => run.gold >= 35),
    UPGRADE_SHRINE: event('UPGRADE_SHRINE', 'Upgrade Shrine', 'The shrine can sharpen one of your techniques.', () => [upgrade('UPGRADE_SHRINE_UPGRADE'), leave()]),
    GOLDEN_IDOL: event('GOLDEN_IDOL', 'Golden Idol', 'A golden statue rests on a pressure plate.', run => run.eventState?.step === 'trap' ? [choice('IDOL_INJURY', 'Take the hit', 'Obtain Injury.'), choice('IDOL_DAMAGE', 'Smash through', `Lose ${worse(run, 25, 35)}% max HP.`), choice('IDOL_MAX_HP', 'Squeeze through', `Lose ${worse(run, 8, 10)}% max HP permanently.`)] : [choice('GOLDEN_IDOL_TAKE', 'Take the idol', 'Obtain Golden Idol. Trigger the trap.'), leave()], run => !run.relics.includes('GOLDEN_IDOL')),
    BIG_FISH: event('BIG_FISH', 'Big Fish', 'Three gifts hang above you. You may take one.', () => [choice('BIG_FISH_BANANA', 'Banana', 'Heal one third of max HP.'), choice('BIG_FISH_DONUT', 'Donut', 'Gain 5 max HP.'), choice('BIG_FISH_BOX', 'Box', 'Obtain a random relic and Regret.')]),
    THE_JOUST: event('THE_JOUST', 'The Joust', 'A wager has been placed. Choose your rider.', () => [choice('THE_JOUST_OWNER', 'Back the owner', 'Pay 50 Gold. 30% chance to win 250.', { disabled: cost(50) }), choice('THE_JOUST_MURDERER', 'Back the murderer', 'Pay 50 Gold. 70% chance to win 100.', { disabled: cost(50) })], run => run.gold >= 50),
    SCRAP_OOZE: event('SCRAP_OOZE', 'Scrap Ooze', 'A relic glints inside the corrosive mass.', run => [choice('SCRAP_OOZE_SEARCH', 'Search', `Lose ${worse(run, 3, 5) + (run.eventState?.attempts ?? 0)} HP. ${Math.min(100, 25 + 10 * (run.eventState?.attempts ?? 0))}% relic chance.`), leave()]),
    LIVING_WALL: event('LIVING_WALL', 'Living Wall', 'Faces in the stone offer to change your deck.', () => [remove('LIVING_WALL_FORGET', 'Forget'), transform('LIVING_WALL_CHANGE'), upgrade('LIVING_WALL_GROW')]),
    THE_SSSSERPENT: event('THE_SSSSERPENT', 'The Ssssserpent', 'A serpent offers gold with a lasting doubt.', run => [choice('THE_SSSSERPENT_AGREE', 'Agree', `Gain ${worse(run, 175, 150)} Gold. Obtain Doubt.`), leave()]),
    FORGOTTEN_ALTAR: event('FORGOTTEN_ALTAR', 'Forgotten Altar', 'The altar demands an offering.', run => [choice('ALTAR_IDOL', 'Offer Golden Idol', 'Replace it with Bloody Idol.', { disabled: r => !r.relics.includes('GOLDEN_IDOL') }), choice('FORGOTTEN_ALTAR_BLOOD', 'Offer blood', `Gain 5 max HP, then lose ${worse(run, 25, 35)}% max HP.`), choice('FORGOTTEN_ALTAR_DESECRATE', 'Desecrate', 'Obtain Decay.')]),
    THE_MAUSOLEUM: event('THE_MAUSOLEUM', 'The Mausoleum', 'A sealed coffin holds a relic.', run => [choice('THE_MAUSOLEUM_OPEN', 'Open it', `Obtain a relic. ${worse(run, 50, 100)}% chance of Writhe.`), leave()]),
    BEGGAR: event('BEGGAR', 'Old Beggar', 'An old beggar promises to ease your burden.', () => [{ ...remove('BEGGAR_GIVE', 'Give', 'Pay 75 Gold. Remove 1 card.'), disabled: cost(75) }, leave()], run => run.gold >= 75),
    ANCIENT_WRITING: event('ANCIENT_WRITING', 'Ancient Writing', 'A faded script describes two disciplines.', () => [remove('WRITING_REMOVE', 'Elegance'), choice('WRITING_UPGRADE', 'Simplicity', 'Upgrade all Strikes and Defends.')]),
    THE_LIBRARY: event('THE_LIBRARY', 'The Library', 'Books and a quiet reading chair await you.', run => [choice('LIBRARY_READ', 'Read', 'Choose 1 of 20 cards.', { requiresSelection: 'reward' }), choice('LIBRARY_SLEEP', 'Sleep', `Heal ${worse(run, 33, 20)}% max HP.`)]),
    GOLDEN_SHRINE: event('GOLDEN_SHRINE', 'Golden Shrine', 'Gold has collected around the shrine.', run => [choice('SHRINE_PRAY', 'Pray', `Gain ${worse(run, 100, 50)} Gold.`), choice('SHRINE_DESECRATE', 'Desecrate', 'Gain 275 Gold. Obtain Regret.'), leave()]),
    TRANSMOGRIFIER: event('TRANSMOGRIFIER', 'Transmogrifier', 'The machine can exchange one card for another.', () => [transform('TRANSMOGRIFY'), leave()]),
    DUPLICATOR: event('DUPLICATOR', 'Duplicator', 'The machine can copy one card, including its upgrades.', () => [choice('DUPLICATE', 'Copy', 'Obtain a copy of a card.', { requiresSelection: 'copy' }), leave()]),
    WHEEL_OF_CHANGE: event('WHEEL_OF_CHANGE', 'Wheel of Change', 'The wheel must turn before you can continue.', run => run.eventState?.step === 'remove' ? [remove('WHEEL_REMOVE', 'Remove a card')] : [choice('WHEEL_SPIN', 'Spin', 'One of six outcomes: Gold, relic, healing, curse, removal, or damage.')]),
    FALLING: event('FALLING', 'Falling', 'You must release something to catch the ledge.', run => {
        const cards = (run.eventState?.cards ?? []).map(id => run.deck.find(c => c.instanceId === id)).filter(c => c !== undefined)
        return cards.length ? cards.map(card => choice(`FALL_${card.instanceId}`, `Lose ${resolveCard(card).name}`, 'Remove this card.')) : [leave()]
    }),
    WINDING_HALLS: event('WINDING_HALLS', 'Winding Halls', 'The corridors fold back on themselves.', run => [choice('HALLS_MADNESS', 'Embrace madness', `Obtain 2 Madness. Lose ${worse(run, 12.5, 18)}% max HP.`), choice('HALLS_WRITHE', 'Rest', `Obtain Writhe. Heal ${worse(run, 25, 20)}% max HP.`), choice('HALLS_MAX_HP', 'Press on', 'Lose 5% max HP permanently.')]),
    MIND_BLOOM: event('MIND_BLOOM', 'Mind Bloom', 'Your memories offer three possible futures.', run => [choice('BLOOM_WAR', 'I am War', 'Fight an Act 1 boss. Obtain a rare relic.'), choice('BLOOM_AWAKE', 'I am Awake', 'Upgrade all cards. You can no longer heal.'), run.floor <= 40 ? choice('BLOOM_RICH', 'I am Rich', 'Gain 999 Gold. Obtain 2 Normality.') : choice('BLOOM_HEALTHY', 'I am Healthy', 'Heal fully. Obtain Doubt.')]),
    THE_MOAI_HEAD: event('THE_MOAI_HEAD', 'The Moai Head', 'A stone face waits for your offering.', run => [choice('MOAI_HP', 'Enter the mouth', `Lose ${worse(run, 12.5, 18)}% max HP permanently. Heal fully.`), choice('MOAI_IDOL', 'Offer Golden Idol', 'Lose Golden Idol. Gain 333 Gold.', { disabled: r => !r.relics.includes('GOLDEN_IDOL') }), leave()], run => run.player.hp <= run.player.maxHp / 2 || run.relics.includes('GOLDEN_IDOL')),
    MYSTERIOUS_SPHERE: event('MYSTERIOUS_SPHERE', 'Mysterious Sphere', 'Two constructs guard a sealed relic.', () => [choice('SPHERE_FIGHT', 'Fight', 'Fight 2 Orb Walkers. Obtain a rare relic.'), leave()]),
    SECRET_PORTAL: event('SECRET_PORTAL', 'Secret Portal', 'The portal leads directly to this act’s boss.', () => [choice('PORTAL_ENTER', 'Enter', 'Skip the remaining rooms and face the boss.'), leave()], run => (run.elapsedSeconds ?? 0) >= 800),
    SENSORY_STONE: event('SENSORY_STONE', 'Sensory Stone', 'The stone reveals memories without a color.', () => [choice('SENSORY_1', 'Recall', 'Choose from 1 colorless card reward.'), choice('SENSORY_2', 'Focus', 'Lose 5 HP. Choose from 2 rewards.'), choice('SENSORY_3', 'Concentrate', 'Lose 10 HP. Choose from 3 rewards.')]),
    RED_MASK_TOMB: event('RED_MASK_TOMB', 'Tomb of Lord Red Mask', 'A red mask rests in the tomb.', run => run.relics.includes('RED_MASK') ? [choice('MASK_WEAR', 'Wear the mask', 'Gain 222 Gold.'), leave()] : [choice('MASK_PAY', 'Offer all Gold', `Pay ${run.gold} Gold. Obtain Red Mask.`), leave()]),
}
