import type { PowerId } from '../../core/state'

export interface HelpEntry { title: string; description: string }
export interface HelpSection { title: string; entries: HelpEntry[] }
export const titleCase = (id: string): string => id.toLowerCase().replaceAll('_', ' ').replace(/\b\w/g, letter => letter.toUpperCase())

/** Player-facing rules, shared by the glossary and live combat inspection. */
export const POWER_HELP: Record<PowerId, string> = {
    STRENGTH: 'Adds this amount to each attack hit. Negative Strength reduces attack damage.',
    DEXTERITY: 'Adds this amount to Block gained from cards. Negative Dexterity reduces it.',
    WEAK: 'Attacks normally deal 25% less damage. The amount is the remaining duration. Relics can change the reduction.',
    VULNERABLE: 'Normally takes 50% more attack damage. The amount is the remaining duration. Relics can change the multiplier.',
    FRAIL: 'Gains 25% less Block from cards for this many turns.',
    ARTIFACT: 'Negates this many applications of a debuff, consuming one charge per application.',
    INTANGIBLE: 'Reduces incoming damage and HP loss to at most 1 per instance while active.',
    POISON: 'Loses this much HP at the start of the enemy turn, bypassing Block. Then Poison decreases by 1.',
    THORNS: 'Deals this much damage back when hit by an attack.',
    BARRICADE: 'Block is kept between turns.',
    METALLICIZE: 'Gains this much Block at the end of the turn.',
    DEMON_FORM: 'Gains this much Strength at the start of each turn.',
    CORRUPTION: 'Skills cost 0 energy and Exhaust when played.',
    FEEL_NO_PAIN: 'Gains this much Block whenever a card is Exhausted.',
    JUGGERNAUT: 'Deals this much damage to a random enemy whenever you gain Block.',
    DARK_EMBRACE: 'Draws this many cards whenever a card is Exhausted.',
    BRUTALITY: 'At the start of each turn, loses this much HP and draws this many cards.',
    BERSERK: 'Gains this much additional energy at the start of each turn.',
    RAGE: 'Gains this much Block whenever you play an Attack this turn.',
    EVOLVE: 'Draws this many cards whenever you draw a Status card.',
    FIRE_BREATHING: 'Deals this much damage to all enemies whenever you draw a Status or Curse.',
    COMBUST: 'At the end of your turn, loses HP and deals this much damage to all enemies.',
    COMBUST_HP_LOSS: 'HP lost each turn from Combust. Included in the Combust explanation.',
    STRENGTH_DOWN_NEXT_TURN: 'Loses this much temporary Strength at the end of your turn.',
    STRENGTH_UP_NEXT_TURN: 'Restores this much Strength at the end of the round.',
    RITUAL: 'Gains this much Strength at the end of the turn.',
    CONFUSION: 'Randomizes the energy cost of cards as they are drawn.',
    HEX: 'Shuffles a Dazed into the draw pile whenever you play a non-Attack card.',
    ENTANGLED: 'Cannot play Attack cards while active.',
    DRAW_REDUCTION: 'Draws fewer cards at the start of the turn.',
    PLATED_ARMOR: 'Gains this much Block at the end of the turn. Loses a stack when an attack causes HP loss.',
    REGENERATE: 'Heals this much HP at the end of the enemy turn.',
    REGENERATION: 'Heals this much HP at the end of your turn, then decreases by 1.',
    RUPTURE: 'Gains this much Strength when a card causes you to lose HP.',
    CURL_UP: 'Gains this much Block the first time an attack causes HP loss, then is removed.',
    NO_DRAW: 'Cannot draw more cards this turn.',
    NO_BLOCK: 'Cannot gain Block from cards while active.',
    SLOW: 'Each card played this turn increases attack damage taken by 10%. Resets each turn.',
    CONSTRICTED: 'Takes this much damage at the end of your turn. Block can absorb it.',
    INVINCIBLE: 'Limits the amount of damage this enemy can take in a turn.',
    DOUBLE_TAP: 'The next indicated number of Attacks this turn are played twice.',
    ACCURACY: 'Shivs deal this much additional damage.',
    AFTER_IMAGE: 'Gains this much Block whenever you play a card.',
    THOUSAND_CUTS: 'Deals this much damage to all enemies whenever you play a card.',
    ENVENOM: 'Applies this much Poison whenever an attack causes HP loss.',
    INFINITE_BLADES: 'Adds this many Shivs to your hand at the start of each turn.',
    NOXIOUS_FUMES: 'Applies this much Poison to every enemy at the start of each turn.',
    TOOLS_OF_THE_TRADE: 'At the start of each turn, draws this many cards, then discards this many.',
    WELL_LAID_PLANS: 'At the end of the turn, choose up to this many cards to Retain.',
    WRAITH_FORM: 'Loses this much Dexterity at the end of each turn. Intangible is tracked separately.',
    CORPSE_EXPLOSION: 'On death, deals damage equal to maximum HP to all other enemies, once per stack.',
    CHOKE: 'Loses this much HP whenever you play a card this turn.',
    BLUR: 'Keeps Block at the start of your next turn. Each stack lasts one turn.',
    BLOCK_NEXT_TURN: 'Gains this much Block at the start of your next turn.',
    ENERGY_NEXT_TURN: 'Gains this much energy at the start of your next turn.',
    DRAW_NEXT_TURN: 'Draws this many additional cards at the start of your next turn.',
    BURST: 'The next indicated number of Skills this turn are played twice.',
    PHANTASMAL_KILLER: 'Grants Double Damage next turn.',
    DOUBLE_DAMAGE: 'Attacks deal double damage while active.',
    BUFFER: 'Prevents this many instances of HP loss.',
    EQUILIBRIUM: 'Retains your hand at the end of the turn while active.',
    ESTABLISHMENT: 'Cards you Retain cost this much less for the rest of combat.',
    DEXTERITY_DOWN: 'Loses this much temporary Dexterity at the end of your turn.',
    FREE_ATTACK: 'The next indicated number of Attacks cost no energy.',
    FOCUS: 'Increases Lightning and Frost output and Dark orb growth. Does not affect Plasma.',
    ELECTRODYNAMICS: 'Lightning orbs hit all enemies instead of a random enemy.',
    LOCK_ON: 'Takes 50% more damage from orbs while active.',
    AMPLIFY: 'The next indicated number of Power cards this turn are played twice.',
    ECHO_FORM: 'The first indicated number of cards played each turn are played twice.',
    DUPLICATION: 'The next indicated number of cards this turn are played twice.',
    REBOUND: 'The next played card returns to the top of the draw pile.',
    BIASED_COGNITION: 'Loses this much Focus at the start of each turn.',
    CREATIVE_AI: 'Adds this many random Power cards to your hand at the start of each turn.',
    HELLO_WORLD: 'Adds this many random Common cards to your hand at the start of each turn.',
    LOOP: 'Triggers your first orb passive this many extra times at the start of each turn.',
    MACHINE_LEARNING: 'Draws this many additional cards at the start of each turn.',
    SELF_REPAIR: 'Heals this much HP when combat ends.',
    STATIC_DISCHARGE: 'Channels this many Lightning orbs when an attack causes HP loss.',
    STORM: 'Channels this many Lightning orbs whenever you play a Power card.',
    HEATSINKS: 'Draws this many cards whenever you play a Power card.',
    MENTAL_FORTRESS: 'Gains this much Block whenever you change stance.',
    RUSHDOWN: 'Draws this many cards whenever you enter Wrath.',
    MANTRA: 'At 10 Mantra, enters Divinity and spends 10 Mantra.',
    BATTLE_HYMN: 'Adds this many Smites to your hand at the start of each turn.',
    BLASPHEMER: 'Suffers lethal HP loss at the start of your next turn.',
    COLLECT: 'Adds an upgraded Miracle to your hand at the start of the turn for this many turns.',
    DEVA_FORM: 'Gains increasing energy at the start of each turn. The energy gain grows by this amount each turn.',
    DEVOTION: 'Gains this much Mantra at the start of each turn.',
    FASTING: 'Gains this much less energy at the start of each turn.',
    FORESIGHT: 'Scries this many cards at the start of each turn.',
    LIKE_WATER: 'Gains this much Block at the end of your turn if you are in Calm.',
    MASTER_REALITY: 'Cards created during combat are upgraded.',
    NIRVANA: 'Gains this much Block whenever you Scry.',
    OMEGA: 'Deals this much damage to all enemies at the end of your turn.',
    STUDY: 'Shuffles this many Insights into the draw pile at the end of your turn.',
    SIMMERING_FURY: 'Enters Wrath and draws this many additional cards next turn.',
    MARK: 'Pressure Points causes marked enemies to lose HP equal to their Mark.',
    TALK_TO_THE_HAND: 'Attacking this enemy grants this much Block.',
    WAVE_OF_THE_HAND: 'Whenever you gain Block this turn, applies this much Weak to all enemies.',
    WREATH_OF_FLAME: 'Your next Attack deals this much additional damage per hit.',
    MAGNETISM: 'Adds this many random Colorless cards to your hand at the start of each turn.',
    MAYHEM: 'Plays this many cards from the top of the draw pile at the start of each turn.',
    PANACHE: 'Every fifth card played in a turn deals this much damage to all enemies.',
    SADISTIC_NATURE: 'Deals this much damage whenever you apply a debuff to an enemy.',
}

export const BASICS: HelpSection[] = [
    { title: 'Your turn', entries: [
        { title: 'Read the enemy intent', description: 'The symbol above an enemy shows its next action. Attack numbers include current modifiers. Block absorbs damage, then HP is lost. Runic Dome hides intents.' },
        { title: 'Spend energy, then end your turn', description: 'The number on a card is its energy cost. Select an Attack, then select its enemy. Cards without a target play immediately. You can also drag cards upward. End Turn lets the enemies act; your next turn refreshes energy and draws cards.' },
        { title: 'Block usually expires', description: 'Unused Block is normally removed at the start of your next turn. Dexterity changes Block from cards. Effects such as Barricade or Blur can preserve it.' },
        { title: 'Inspect before committing', description: 'Hover over a card, tap its ? control, or press Alt plus its hand number for full rules. Select Effects below a combatant to read status descriptions. Escape cancels targeting or closes inspection before opening the pause menu.' },
    ] },
    { title: 'Cards and piles', entries: [
        { title: 'Draw, discard and Exhaust', description: 'Played cards and cards left in your hand usually go to the discard pile. When the draw pile runs out, the discard pile is shuffled into it. Exhaust removes a card for this combat. Draw Pile hides the actual order unless you have Frozen Eye.' },
        { title: 'Retain, Ethereal and Innate', description: 'Retain keeps a card in your hand between turns. An unplayed Ethereal card Exhausts at the end of the turn. Innate cards begin in your opening hand. Your hand can hold at most 10 cards.' },
        { title: 'Upgrades and Scry', description: 'Campfire upgrades stay for the run. Upgrades applied during combat, such as Armaments, last only for that fight. Scry shows the top cards of your draw pile and lets you discard chosen cards before drawing. Card choices show how many selections are required; Confirm completes the choice.' },
        { title: 'Potions and relics', description: 'Potions are consumable. Select one to inspect, use, or discard it; targeted potions need an enemy. Relics provide lasting effects. Their descriptions are in your Bag. Some relics change the usual combat rules.' },
    ] },
    { title: 'The climb', entries: [
        { title: 'Choose a route', description: 'Follow connected rooms upward. Monsters give rewards. Elites are tougher and give relics. Campfires let you rest or upgrade. Shops sell cards, potions and relics, and can remove a card. Question marks lead to events or other encounters.' },
        { title: 'Build a focused deck', description: 'You can skip a card reward. A smaller deck draws key cards more often. Balance damage, defense and ways to use your character mechanics. Boss relics offer powerful benefits with tradeoffs.' },
        { title: 'Keys and the final act', description: 'After the Heart route is unlocked, collect the Ruby key at a campfire, the Sapphire key instead of a chest relic, and the Emerald key from a burning elite. All three are needed for Act 4.' },
        { title: 'Progress and saving', description: 'Standard runs qualify for Ascension, Heart progression and standard achievements. Seeded and Custom runs still earn relic unlock XP; a Daily victory has its own achievement. The game saves on this device. Continue restarts an unfinished fight from its room entry. Use Settings to export a profile backup.' },
    ] },
    { title: 'Character mechanics', entries: [
        { title: 'Ironclad', description: 'Strength adds damage to each attack hit. Exhaust can trigger Block and draw effects. Some cards spend HP for stronger effects; check your remaining health before playing them.' },
        { title: 'Silent', description: 'Poison bypasses Block, then decreases by 1 after its tick. Shivs are zero-cost Attacks that Exhaust. Discarding can enable card effects; Retain lets you save key cards for later.' },
        { title: 'Defect', description: 'Channel fills an orb slot. If all slots are full, the first orb Evokes and leaves. Lightning damages enemies, Frost gives Block, Dark stores damage, and Plasma gives energy. Focus improves Lightning, Frost and Dark growth. See your Effects for current orb values.' },
        { title: 'Watcher', description: 'Wrath doubles attack damage dealt and taken. Leaving Calm normally grants 2 energy. Divinity grants 3 energy on entry and triples attack damage, then ends next turn. Gaining 10 Mantra enters Divinity. Relics may change these rules.' },
    ] },
]
export const GLOSSARY: HelpSection[] = [{ title: 'Status effects', entries: (Object.entries(POWER_HELP) as [PowerId, string][])
    .filter(([id]) => id !== 'COMBUST_HP_LOSS').map(([id, description]) => ({ title: titleCase(id), description }))
    .sort((a, b) => a.title.localeCompare(b.title)) }]
